### ISSUE TITLE
player_active_character missing

### ISSUE THREAD

**Issue by sahammer** [adaliszk/valheim-server#50]
First off - thanks so much for this monitoring companion!

I recently installed it, using an LGSM deployment of Valheim and `player_active_character` appears to be missing. I assume this would only show *active* players on the server. Is the container deployment of Valheim required for this metric?

Thanks in advance!

**Comment by adaliszk** [comment]
Hey,

I am sorry for not noticing you earlier. Quickly looking into the issue seems that I had that metric at some point, but it got lost. The particular log line I was using does not require my server image to be used; most things should work fine, and only things that my image prints on its own are not available for other installations, such as world disk usage and backup statistics.

I am in progress with a rework of the whole repository, but I will try to include a quick fix for this!

**Comment by adaliszk** [comment]
Upon investigation, I have had different metrics for the same purpose that was not documented:
* `player_character` by `steam_id`, `player_id`, `player_nick`

Essentially, you can get the particular player character's nickname by either the ZDOID or the STEAMID and retrieve the other labels for mapping. This metric keeps the mapping as long as possible, and you can cross-reference the active/online state with `player_connected_last` and `player_disconnected_last`.

Does this solve your needs?

**Comment by sahammer** [comment]
Hmmmm... it should. I'll have to play around with the dashboard a bit and see, thanks for the updates! I'll pull the latest container :)

**Comment by adaliszk** [comment]
Sounds good. Feel free to drop in any new boards into the repo. I want to update the one I have here, perhaps even offering a few other types of dashboards, but that comes after I managed to push through my 1.0 branch 😉 

I'll close this issue, and please open a new one for any missing metric (or metric collections) you would like to have!
